state: 'NY'
var_list:
    - 'B01003_001E'
    - 'B25001_001E'
    - 'B25035_001E'
    - 'B19051_001E'
    - 'B19013_001E'
    - 'B01002_001E'
    - 'B02001_002E'
    - 'B02001_003E'
    - 'B02001_004E'
    - 'B02001_005E'
    - 'B02001_006E'
    - 'B02001_007E'
    - 'B02001_008E'
    - 'B02001_009E'
    - 'B02001_010E'
    - 'B25058_001E'
data_dir: 'data/'
db:
    host: 'mlpolicylab.db.dssg.io'
    user: 'jingyuny'
    database: 'epa3_database'
schema_name: 'jingyuny'
table_name: 'acs'
csv_filename: 'data/data.csv'
use_saved_data: false
